#ifndef _GAME_WINDOW_ENUM_H
#define _GAME_WINDOW_ENUM_H

typedef enum {
    HUWIN_LANG_NULL = -1,
    HUWIN_LANG_JAPAN, //0
    HUWIN_LANG_ENGLISH, //1
    HUWIN_LANG_GERMANY, //2
    HUWIN_LANG_FRANCE, //3
    HUWIN_LANG_ITALY, //4
    HUWIN_LANG_SPAIN //5
} HUWIN_LANG;

typedef enum {
    HUWIN_FRAME_DEFAULT, //0
    HUWIN_FRAME_DARK, //1
    HUWIN_FRAME_WARN, //2
    HUWIN_FRAME_NIGHT, //3
    HUWIN_FRAME_DAY, //4
    HUWIN_FRAME_DAYNIGHT, //5
    HUWIN_FRAME_MAX //6
} HUWIN_FRAME;

typedef enum {
    HUWIN_SPEAKER_NULL = -1,
    HUWIN_SPEAKER_HANACHAN, //0
    HUWIN_SPEAKER_HANACHAN_STAR, //1
    HUWIN_SPEAKER_KURIBO, //2
    HUWIN_SPEAKER_NOKONOKO_START, //3
    HUWIN_SPEAKER_KOKAMEKKU, //4
    HUWIN_SPEAKER_KAMEKKU, //5
    HUWIN_SPEAKER_SUN, //6
    HUWIN_SPEAKER_MOON, //7
    HUWIN_SPEAKER_NOKONOKO, //8
    HUWIN_SPEAKER_HEIHO, //9
    HUWIN_SPEAKER_TERESA, //10
    HUWIN_SPEAKER_BATTAN, //11
    HUWIN_SPEAKER_DONKEY, //12
    HUWIN_SPEAKER_KOOPA, //13
    HUWIN_SPEAKER_OYAMA, //14
    HUWIN_SPEAKER_YARIHO, //15
    HUWIN_SPEAKER_UKKI, //16
    HUWIN_SPEAKER_KINOKIO, //17
    HUWIN_SPEAKER_WARUKIO, //18
    HUWIN_SPEAKER_MINIKOOPA_R, //19
    HUWIN_SPEAKER_MINIKOOPA_G, //20
    HUWIN_SPEAKER_MINIKOOPA_B, //21
    HUWIN_SPEAKER_WANWAN, //22
    HUWIN_SPEAKER_SUNMOON, //23
    HUWIN_SPEAKER_MAX //24
} HUWIN_SPEAKER;

#endif
